x="""
查询汉堡类菜单请输入1
查新小食类菜单请输入2
查询饮料类菜单请输入3
若不查询请输入0
    """
print(x)
num=input('请输入：')
int_num=int(num)
list_food=("感谢你的使用"
           """
           香辣鸡腿堡
           劲脆鸡腿堡
           新奥尔良鸡腿堡
           半鸡半虾堡""",
           """
           薯条
           黄金鸡块
           香甜李米邦
           """,
           """
           可口可乐
           九珍果汁
           经典咖啡
           """,)
result=list_food[int_num]
print(result)

